Licorera Pepinos/Licorera/Capa_Presentacion/Models/Usuario.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Capa_Presentacion.Models
{
    public class Usuario
    {
        public int Id { get; set; }

        public int Cedula { get; set; }

        public string Nombre { get; set; }

        public string Apellido1 { get; set; }

        public string Apellido2 { get; set; }

        public int Telefono { get; set; }

        public DateTime FecNacimiento { get; set; }

        public string Email { get; set; }

        public string Pass { get; set; }

        public int IdRol { get; set; }
    }
}

Licorera Pepinos/Licorera/Capa_Presentacion/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Capa_Presentacion.Controllers
{
    public class HomeController : Controller
    {
        // GET: Home
        public ActionResult Index()
        {
            return View();
        }
    }
}

Licorera Pepinos/Licorera/Capa_Presentacion/Controllers/LoginController.cs
using Capa_Logica;
using Capa_Presentacion.Models;
using Capa_Presentacion.Tools;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.UI.WebControls;

namespace Capa_Presentacion.Controllers
{
    public class LoginController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
    }
}

Licorera Pepinos/Licorera/Capa_Presentacion/Controllers/UsuarioController.cs
using Capa_Logica;
using Capa_Presentacion.Models;
using Capa_Presentacion.Tools;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Capa_Presentacion.Controllers
{
    public class UsuarioController : Controller
    {
        // GET: Usuario
        public ActionResult Index()
        {
            try
            {
                List<Usuario> listaUsuarios = new List<Usuario>();
                clsUsuario usuario = new clsUsuario();
                var data = usuario.ConsultarUsuarios().ToList();
                foreach (var item in data)
                {
                    Usuario modelo = new Usuario();
                    modelo.Id = item.ID;
                    modelo.Cedula = item.Cedula;
                    modelo.Nombre = item.Nombre;
                    modelo.Apellido1 = item.Apellido1;
                    modelo.Apellido2 = item.Apellido2;
                    modelo.Telefono = item.Telefono;
                    modelo.FecNacimiento = item.FecNacimiento;
                    modelo.Email = item.Email;
                    modelo.Pass = item.Pass;
                    modelo.IdRol = item.IdRol;

                    listaUsuarios.Add(modelo);
                }
                return View(listaUsuarios);
            }
            catch
            {
                return RedirectToAction("Error");
            }
        }

        public ActionResult Crear()
        {
            try
            {
                clsRol listaRoles = new clsRol();
                ViewBag.ListaTiposRoles = listaRoles.ConsultarRoles();
                return View();
            }
            catch
            {
                return RedirectToAction("Error");
            }
        }

        [HttpPost]
        public ActionResult Crear(Usuario usuario)
        {
            try
            {
                clsUsuario objUsuario = new clsUsuario();
                bool resultado = objUsuario.AgregarUsuario(usuario.Cedula, usuario.Nombre, usuario.Apellido1, usuario.Apellido2, usuario.Telefono, usuario.FecNacimiento, Seguridad.Encriptar(usuario.Email), Seguridad.Encriptar(usuario.Pass), usuario.IdRol);
                if (resultado)
                {
                    return RedirectToAction("Index");
                } else
                {
                    return RedirectToAction("Error");
                }
            }
            catch
            {
                throw;
            }
        }

        public ActionResult Editar(int Id)
        {
            try
            {
                clsUsuario usuario = new clsUsuario();
                clsRol listaRoles = new clsRol();
                ViewBag.ListaTiposRoles = listaRoles.ConsultarRoles();
                var dato = usuario.ConsultarUsuario(Id);
                Usuario modelo = new Usuario();
                modelo.Id = dato[0].ID;
                modelo.Cedula = dato[0].Cedula;
                modelo.Nombre = dato[0].Nombre;
                modelo.Apellido1 = dato[0].Apellido1;
                modelo.Apellido2 = dato[0].Apellido2;
                modelo.Telefono = dato[0].Telefono;
                modelo.FecNacimiento = dato[0].FecNacimiento;
                modelo.Email = Seguridad.Desencriptar(dato[0].Email);
                modelo.Pass = dato[0].Pass;
                modelo.IdRol = dato[0].IdRol;

                return View(modelo);

            }
            catch
            {
                return RedirectToAction("Error");
            }
        }

        [HttpPost]
        public ActionResult Editar(int Id, Usuario usuario)
        {
            try
            {
                clsUsuario objUsuario = new clsUsuario();
                bool resultado = objUsuario.ActualizarUsuario(usuario.Id, usuario.Cedula, usuario.Nombre, usuario.Apellido1, usuario.Apellido2, usuario.Telefono, usuario.FecNacimiento, usuario.Email, usuario.Pass, usuario.IdRol);
                if (resultado)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    return RedirectToAction("Error");
                }
            }
            catch
            {
                return RedirectToAction("Error");
            }
        }

        public ActionResult Eliminar(int Id)
        {
            try
            {
                clsUsuario usuario = new clsUsuario();
                bool resultado = usuario.EliminarUsuario(Id);
                if (resultado)
                {
                    return RedirectToAction("Index");
                } else
                {
                    return RedirectToAction("Error");
                }
            }
            catch
            {
                return RedirectToAction("Error");
            }
        }
    }
}

Licorera Pepinos/Licorera/Capa_Presentacion/Views/Home/Index.cshtml

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Administrador.cshtml";
}
<!-- Content Header (Page header) -->
<section class="content-header">
    <h1>
        Blank page
        <small>it all starts here</small>
    </h1>
    <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
        <li><a href="#">Examples</a></li>
        <li class="active">Blank page</li>
    </ol>
</section>

<!-- Main content -->
<section class="content">

    <!-- Default box -->
    <div class="box">
        <div class="box-header with-border">
            <h3 class="box-title">Title</h3>

            <div class="box-tools pull-right">
                <button type="button" class="btn btn-box-tool" data-widget="collapse" data-toggle="tooltip" title="Collapse">
                    <i class="fa fa-minus"></i>
                </button>
                <button type="button" class="btn btn-box-tool" data-widget="remove" data-toggle="tooltip" title="Remove">
                    <i class="fa fa-times"></i>
                </button>
            </div>
        </div>
        <div class="box-body">
            Start creating your amazing application!
        </div>
        <!-- /.box-body -->
        <div class="box-footer">
            Footer
        </div>
        <!-- /.box-footer-->
    </div>
    <!-- /.box -->

</section>
<!-- /.content -->

Licorera Pepinos/Licorera/Capa_Presentacion/Views/Login/Index.cshtml
@model Capa_Presentacion.Models.Usuario
@{
    Layout = null;
}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>AdminLTE 2 | Log in</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <!-- Bootstrap 3.3.6 -->
    <link rel="stylesheet" href="../../Content/bootstrap/css/bootstrap.min.css">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.5.0/css/font-awesome.min.css">
    <!-- Ionicons -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="../../Content/dist/css/AdminLTE.min.css">
    <!-- iCheck -->
    <link rel="stylesheet" href="../../Content/plugins/iCheck/square/blue.css">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<body class="hold-transition login-page" style="margin:0">
    <div class="login-box">
        <div class="login-logo">
            <a href="../../index2.html"><b>Licorera </b>Pepinos</a>
        </div>
        <!-- /.login-logo -->
        <div class="login-box-body">
            <p class="login-box-msg">Ingrese sus credenciales</p>

            <form action="~/Usuario/Index" method="post">
                <div class="form-group has-feedback">
                    <input type="email" class="form-control" placeholder="Correo" id="Email">
                    <span class="glyphicon glyphicon-envelope form-control-feedback"></span>
                </div>
                <div class="form-group has-feedback">
                    <input type="password" class="form-control" placeholder="Contraseña" id="Pass">
                    <span class="glyphicon glyphicon-lock form-control-feedback"></span>
                </div>
                <div class="form-group has-feedback">
                    <a href="@Url.Action("Reenviar", "Login")" class="text-center" style="color:#ffffff">¿Olvidó su contraseña?</a>
                </div>
                <div class="form-group has-feedback">
                    <button type="submit" class="btn btn-primary btn-block btn-flat">Ingresar</button>
                    <button type="submit" class="btn btn-warning btn-block btn-flat">Registrarme</button>
                </div>
            </form>
        </div>
        <!-- /.login-box-body -->
    </div>
    <!-- /.login-box -->
    <!-- jQuery 2.2.3 -->
    <script src="../../Content/plugins/jQuery/jquery-2.2.3.min.js"></script>
    <!-- Bootstrap 3.3.6 -->
    <script src="../../Content/bootstrap/js/bootstrap.min.js"></script>
    <!-- iCheck -->
    <script src="../../Content/plugins/iCheck/icheck.min.js"></script>
    <script>
    $(function () {
            $('input').iCheck({
                checkboxClass: 'icheckbox_square-blue',
                radioClass: 'iradio_square-blue',
                increaseArea: '20%' // optional
            });
        });</script>
</body>
</html>


Licorera Pepinos/Licorera/Capa_Presentacion/Views/Usuario/Crear.cshtml
@model Capa_Presentacion.Models.Usuario

@{
    ViewBag.Title = "Crear";
    Layout = "~/Views/Shared/_Administrador.cshtml";
}

<h2>Crear</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>Usuario</h4>
    <hr />
    @Html.Hidden("ID", 0)
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.Cedula, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Cedula, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Cedula, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Nombre, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Apellido1, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Apellido1, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Apellido1, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Apellido2, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Apellido2, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Apellido2, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Telefono, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Telefono, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Telefono, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.FecNacimiento, htmlAttributes: new { @class = "control-label col-md-2"})
        <div class="col-md-10">
            @Html.EditorFor(model => model.FecNacimiento, new { htmlAttributes = new { @class = "form-control", @type = "date" } })
            @Html.ValidationMessageFor(model => model.FecNacimiento, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Pass, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Pass, new { htmlAttributes = new { @class = "form-control", @type = "password"} })
            @Html.ValidationMessageFor(model => model.Pass, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.IdRol, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownListFor(model => model.IdRol, new SelectList(ViewBag.ListaTiposRoles, "ID", "Nombre"), "Seleccione", new { @class = "form-control", style = "font-size: 14px; font-weight:700" })
            @Html.ValidationMessageFor(model => model.IdRol, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Licorera Pepinos/Licorera/Capa_Presentacion/Views/Usuario/Editar.cshtml
@model Capa_Presentacion.Models.Usuario

@{
    ViewBag.Title = "Editar";
    Layout = "~/Views/Shared/_Administrador.cshtml";
}

<h2>Editar</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Usuario</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Cedula, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Cedula, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Cedula, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Nombre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Apellido1, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Apellido1, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Apellido1, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Apellido2, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Apellido2, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Apellido2, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Telefono, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Telefono, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Telefono, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FecNacimiento, htmlAttributes: new { @class = "control-label col-md-2", @type = "date"})
            <div class="col-md-10">
                @Html.EditorFor(model => model.FecNacimiento, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FecNacimiento, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Pass, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Pass, new { htmlAttributes = new { @class = "form-control", @type = "password" } })
                @Html.ValidationMessageFor(model => model.Pass, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IdRol, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.IdRol, new SelectList(ViewBag.ListaTiposRoles, "ID", "Nombre"), "Seleccione", new { @class = "form-control", style = "font-size: 14px; font-weight:700" })
                @Html.ValidationMessageFor(model => model.IdRol, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Licorera Pepinos/Licorera/Capa_Presentacion/Views/Usuario/Index.cshtml
@model IEnumerable<Capa_Presentacion.Models.Usuario>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Administrador.cshtml";
}

<section class="content">
    <div class="row">
        <div class="col-xs-12">

            <div>
                <div class="box-header">
                    <h3 class="box-title">USUARIOS</h3>
                </div>
                <a class="btn btn-success" href="~/Usuario/Crear">
                    <span class="fa fa-plus"> Agregar</span>
                </a>
                <!-- /.box-header -->
                <div class="box-body">
                    <table id="example1" class="table table-bordered table-striped">
                        <thead>
                            <tr>
                                <th>
                                    @Html.DisplayNameFor(model => model.Cedula)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.Nombre)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.Telefono)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.FecNacimiento)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.IdRol)
                                </th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {
                                <tr>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Cedula)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Nombre)
                                        @Html.DisplayFor(modelItem => item.Apellido1)
                                        @Html.DisplayFor(modelItem => item.Apellido2)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Telefono)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.FecNacimiento)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.IdRol)
                                    </td>
                                    <td>
                                        @Html.ActionLink("Actualizar", "Editar", new { id = item.Id }, new { @class = "btn btn-success btn-sm", style = "background:#f39c12; border-color:#f39c12" }) |
                                        @Html.ActionLink("Eliminar", "Eliminar", new { id = item.Id }, new { @class = "btn btn-danger btn-sm", style = "background:#dd4b39; border-color:#dd4b39", onclick = "return Confirmar(this);" })
                                    </td>
                                </tr>
                            }
                        </tbody>
                        <tfoot>
                            <tr>
                                <th>
                                    @Html.DisplayNameFor(model => model.Cedula)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.Nombre)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.Telefono)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.FecNacimiento)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.IdRol)
                                </th>
                                <th></th>
                            </tr>
                        </tfoot>
                    </table>
                </div>
                <!-- /.box-body -->
            </div>
            <!-- /.box -->
        </div>
        <!-- /.col -->
    </div>
    <!-- /.row -->
</section>
